### ISSUE TITLE
TodosDto 내 Request 스태틱 클래스 질문

### ISSUE THREAD

**Issue by dyjeong365** [dayoungee/api-todoapp#4]
[해당코드](https://github.com/dayoungee/api-todoapp/blob/f60b7f50b0705e2450b8d831ea5e4176130360ce/src/main/java/com/codestates/todoapp/todos/TodosDto.java#LL11C5-L11C33)

요구사항에서는 중복이지만 추후 확장을 위해 필요한 핸들러 메서드 단위로 분리하면 어떨까요?

**Comment by dayoungee** [comment]
조언 감사합니다! 동영님!!
